name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  $ECR_REGISTRY: ${{ secrets.ECR_REPOSITORY_URI }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Pull Nginx image
      run: docker pull nginx 
      
    - name: Tag Nginx image
      run: docker tag nginx:latest nagoorbasha1476/nginx:latest
      
    - name: push the image to docker
      run: docker push nagoorbasha1476/nginx:latest  
    
    - name: fdfv
      run: aws ecr get-login-password --region $AWS_REGION | docker login nagoorbasha1476 AWS --password-stdin $ECR_REGISTRY

    - name: Push Docker image to Amazon ECR
      run: docker push $ECR_REGISTRY/nginx:$GITHUB_SHA
  
