jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      env:
        DOCKER_REGISTRY: mydockerregistry.com
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Build Docker image
        docker build -t myimage:latest .

        # Login to Docker registry
        docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        # Push Docker image
        docker tag myimage:latest $DOCKER_REGISTRY/myimage:latest
        docker push $DOCKER_REGISTRY/myimage:latest
