jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      env:
        DOCKER_REGISTRY: https://hub.docker.com/repositories/nagoorbasha1476
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Build Docker image
        docker build -t nginx:latest .

        # Login to Docker registry
        docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        # Push Docker image
        docker tag nginx:latest $DOCKER_REGISTRY/nginx:latest
        docker push $DOCKER_REGISTRY/nginx:latest
